#include<iostream>
#include<vector>
using namespace std;
void Permutation(vector<int> A,int k,vector<vector<int>> &v){
    if(k>=A.size()){
        v.push_back(A);
        return;
    }
    // All the permutations we want will be generated by rearranging the exisisting numbers in different ways
    // So swap each position with every other location. 
    for(int i=k;i<A.size();i++){
        swap(A[k],A[i]);
        Permutation(A,k+1,v);
        swap(A[k],A[i]);
    }
    return;
}
vector<vector<int>> generatePermutations(vector<int> A){
    vector<vector<int>> answer;
    int n = A.size();
    Permutation(A,0,answer);
    return answer;
}
int main(){
    vector<int> A = {1,2,3};
    vector<vector<int>> perm = generatePermutations(A);
    for(int i=0;i<perm.size();i++){
        for(int j=0;j<perm[i].size();j++){
            cout<<perm[i][j];
        }
        cout<<endl;
    }
    return 0;
}